name: observatory
transformers:
- dart_to_js_script_rewriter
- $dart2js:
    suppressWarnings: false
    commandLineOptions: [--show-package-warnings]
dependencies:
  args: ^0.13.2
  charted: ^0.4.8
  unittest: < 0.12.0
  usage: ^1.2.0
